taxiapp/config/routes.rb
Rails.application.routes.draw do

  get 'order/client'
  root 'pages#home'
  get 'pages/home'
  get 'pages/viaja'
  get 'pages/conduce'
  get 'pages/contacto'
  get 'user/index'
  get 'user/newclient'
  get 'user/newdriver'
  post 'user/create'
  get 'user/editclient'
  get 'user/editdriver'
  post 'user/update'
  post 'user/login'
  get 'user/logout'
  get 'user/show'
  
  resources :user

  get 'order/admin'
  get 'order/driver'
  post 'order/create'
  get 'order/historialclient'
  get 'order/historialdriver'
  get 'order/edit'
  post 'order/update'
  get 'order/dash'
  get 'order/reportclient'
  get 'order/reportorder'
  post 'order/changecli'
  post 'order/cancelcli'
  post 'order/canceldri'
  post 'order/edituseradmin'
  post 'order/deluseradmin'
  post 'order/editorderadmin'
  post 'order/delorderadmin'
  post 'order/editordercli'
  post 'order/delordercli'
  post 'order/delorderdri'
  
  resources :order
  
  
   

end

taxiapp/app/views/pages/conduce.html.erb
<div class="jumbotron bgimagen2">
    <div class="container">
        <%= link_to "Registrese como Chofer", user_newdriver_path, :class => "btn btn-blue btn-lg btn-huge lato textobutton "  %>
    </div>
</div>

<br/>

<div class="container">
    <div class="col-md-12"></div>
    <!-- Example row of columns -->
    <div class="col-md-1"></div>
    <div class="row">
        <div class="col-md-5">
            <h2>Gana dinero cómo tú quieras</h2>
            <p>Es fácil ganar dinero ayudando a la gente a desplazarse por la ciudad. La cantidad de dinero dependerá totalmente de ti. Con tantos pasajeros en la ciudad, hay oportunidades en todas partes.</p>
        </div>
        <div class="col-md-5">
            <h2>Establece tu propio horario</h2>
            <p>Cuando conduces con TaxiExpress, tú decides cuándo y cómo quieres trabajar. Así, nunca tendrás que elegir entre ganarte la vida o vivir la vida.</p>
        </div>
        <div class="col-md-1"></div>       
    </div>
</div>

taxiapp/app/views/pages/contacto.html.erb
<section class="container-fluid"style="background:none;">

        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center">CONTACTENOS</h1>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">

                <div class="row form-group">
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Nombre" required="">
                    </div>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="middleName" name="firstName" placeholder="Apellido" required="">
                    </div>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="lastName" name="lastName" placeholder="DNI" required="">
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-6">
                        <input type="email" class="form-control" name="email" placeholder="Email" required="">
                    </div>
                    <div class="col-sm-5">
                        <input type="email" class="form-control" name="phone" placeholder="Celular" required="">
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-11">
                        <input type="homepage" class="form-control" placeholder="Descripcion" required="">
                    </div>
                </div>
 
                <div class="row form-group">
                    <div class="col-sm-11">
                        <button class="btn btn-primary btn-lg btn-block">Contactanos</button>
                    </div>
                </div>
                
                <div class="row form-group">
                    <iframe  width="860" height="500" style="margin:auto; padding:10px;" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=Universidad%20Peruana%20de%20Ciencias%20Aplicadas&key=AIzaSyAEz6ZPTS0y5N4hnuVx2nVqlK2tXsfftmQ" allowfullscreen></iframe>                    
                </div>
            </div>
            <div class="col-sm-3"></div>  
            </div>
        </div>
</section>

taxiapp/app/views/pages/home.html.erb
<div class="v-center">
    <h1 class="text-center">TAXI EXPRESS</h1>
    <h2 class="text-center lato animate slideInDown">A cualquier lugar<b> en un solo toque </b></h2>
    <p class="text-center">
        <br>
            <%= link_to "Registrese como Cliente", user_newclient_path, :class => "btn btn-blue btn-lg btn-huge lato"  %>
            <%= link_to "Registrese como Chofer", user_newdriver_path, :class => "btn btn-blue btn-lg btn-huge lato"  %>
    </p>
</div>

taxiapp/app/views/pages/viaja.html.erb
  <body>
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron bgimagen3" >
      <div class="container">
          <%= link_to "Registrese como Cliente", user_newclient_path, :class => "btn btn-blue btn-lg btn-huge lato textobutton "  %>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        
        <div class="col-md-4">
          <div class="border-icon"></div>
          <h2 class="text-center">Aprieta un botón y consigue un viaje</h2>
          <p>Elige tu viaje y establece tu ubicación. Verás la foto de tu conductor y la información de su vehículo, y también podrás controlar su llegada en el mapa. </p>
        </div>
        
        <div class="col-md-4">
          <div class="border-icon"></div>
          <h2 class="text-center">Sin efectivo, sin propina, sin complicaciones</h2>
          <p>Cuando llegues a tu destino solo te tendrás que bajar del coche. Nosotros cobraremos el viaje automáticamente a la tarjeta de crédito registrada. Y no es necesario dejar propina.</p>
       </div>
       
        <div class="col-md-4">
          <div class="border-icon"></div>
          <h2 class="text-center">Tú calificas, nosotros escuchamos</h2>
          <p>Valora a tu conductor y deja un comentario anónimo sobre tu viaje. Tus comentarios nos ayudan a que cada viaje sea una experiencia de 5 estrellas.</p>
        </div>
        
      </div>

  </body>