taxiapp/config/routes.rb
Rails.application.routes.draw do

  get 'order/client'
  root 'pages#home'
  get 'pages/home'
  get 'pages/viaja'
  get 'pages/conduce'
  get 'pages/contacto'
  get 'user/index'
  get 'user/newclient'
  get 'user/newdriver'
  post 'user/create'
  get 'user/editclient'
  get 'user/editdriver'
  post 'user/update'
  post 'user/login'
  get 'user/logout'
  get 'user/show'
  
  resources :user

  get 'order/admin'
  get 'order/driver'
  post 'order/create'
  get 'order/historialclient'
  get 'order/historialdriver'
  get 'order/edit'
  post 'order/update'
  get 'order/dash'
  get 'order/reportclient'
  get 'order/reportorder'
  post 'order/changecli'
  post 'order/cancelcli'
  post 'order/canceldri'
  post 'order/edituseradmin'
  post 'order/deluseradmin'
  post 'order/editorderadmin'
  post 'order/delorderadmin'
  post 'order/editordercli'
  post 'order/delordercli'
  post 'order/delorderdri'
  
  resources :order
  
  
   

end

taxiapp/app/models/user.rb
class User < ActiveRecord::Base
    has_many :order
    validates :email, presence: true
    validates :passwd, presence: true
    validates :first_name, presence: true
    validates :credit_card, presence: true
    validates :expiration_credit_card, presence: true
    validates :cvv, presence: true
end

taxiapp/app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def newclient
    @order = Order.new
    @user =  User.new
  end
  
  def newdriver
    @order = Order.new
    @user =  User.new
  end
  
  def create
    
    @order = Order.new
    @user = User.new
    
    if params[:user][:email] != ""
      if params[:user][:passwd] != ""
        if params[:user][:first_name] != ""
          if params[:user][:credit_card] != ""
            if params[:user][:expiration_credit_card] != ""
              if params[:user][:cvv] != ""
              
                @user = User.new(email:params[:user][:email], 
                               passwd:params[:user][:passwd],
                               first_name:params[:user][:first_name],
                               last_name:params[:user][:last_name],
                               role:params[:user][:role],
                               phone:params[:user][:phone],
                               credit_card:params[:user][:credit_card],
                               expiration_credit_card:params[:user][:expiration_credit_card],
                               cvv:params[:user][:cvv],
                               license:params[:user][:license],
                               soat:params[:user][:soat],
                               brand:params[:user][:brand],
                               modele:params[:user][:modele],
                               plate:params[:user][:plate],
                               state_driver:"Libre")
                               
                if @user.save()
                  @alertType = ""
                  @alertMessage = ""
                  
                  login()
                end 
                
              elsif
                @alertType = "danger"
                @alertMessage = "Por favor ingrese el codigo secreto de su tardejeta de credito."
                if params[:user][:role] == 2 then render :action => "newclient" else render :action => "newdriver" end
              end
                
            elsif
              @alertType = "danger"
              @alertMessage = "Por favor ingrese la fecha de caducidad de la tardejeta de credito."
              if params[:user][:role] == 2 then render :action => "newclient" else render :action => "newdriver" end
            end
              
          elsif
            @alertType = "danger"
            @alertMessage = "Por favor ingrese el numero de su tarjeta."
            if params[:user][:role] == 2 then render :action => "newclient" else render :action => "newdriver" end
          end
            
        elsif
          @alertType = "danger"
          @alertMessage = "Por favor ingrese sus nombres."
          if params[:user][:role] == 2 then render :action => "newclient" else render :action => "newdriver" end
        end
        
      elsif
        @alertType = "danger"
        @alertMessage = "Por favor ingrese una clave para su cuenta."
        if params[:user][:role] == 2 then render :action => "newclient" else render :action => "newdriver" end
      end
    
    elsif
      @alertType = "danger"
      @alertMessage = "Por favor ingrese un email valido."
      if params[:user][:role] == 2 then render :action => "newclient" else render :action => "newdriver" end
    end
    
  end
  
  def editclient
    @order = Order.new
    @user = User.find(session[:current_user]['id'])
  end
  
  def editdriver
    @order = Order.new
    @user = User.find(session[:current_user]['id'])
  end
  
  def update
    
    @order = Order.new
    @user = User.new
    
    if params[:user][:email] != ""
      if params[:user][:passwd] != ""
        if params[:user][:first_name] != ""
          if params[:user][:credit_card] != ""
            if params[:user][:expiration_credit_card] != ""
              if params[:user][:cvv] != ""
    
                @user = User.find(session[:current_user]['id'])
                @user.email = params[:user][:email]
                @user.passwd = params[:user][:passwd]
                @user.first_name = params[:user][:first_name]
                @user.last_name = params[:user][:last_name]
                @user.phone = params[:user][:phone]
                @user.credit_card = params[:user][:credit_card]
                @user.expiration_credit_card = params[:user][:expiration_credit_card]
                @user.cvv = params[:user][:cvv]
                @user.license = params[:user][:license]
                @user.soat = params[:user][:soat]
                @user.brand = params[:user][:brand]
                @user.modele = params[:user][:modele]
                @user.plate = params[:user][:plate]
                                 
                if @user.save()
                  @alertType = "success"
                  @alertMessage = "Se modificaron correctamente sus datos."
                end
                
              elsif
                @alertType = "danger"
                @alertMessage = "Por favor ingrese el codigo secreto de su tardejeta de credito."
              end
                
            elsif
              @alertType = "danger"
              @alertMessage = "Por favor ingrese la fecha de caducidad de la tardejeta de credito."
            end
              
          elsif
            @alertType = "danger"
            @alertMessage = "Por favor ingrese el numero de su tarjeta."
          end
            
        elsif
          @alertType = "danger"
          @alertMessage = "Por favor ingrese sus nombres."
        end
        
      elsif
        @alertType = "danger"
        @alertMessage = "Por favor ingrese una clave para su cuenta."
      end
    
    elsif
      @alertType = "danger"
      @alertMessage = "Por favor ingrese un email valido."
    end
    
    if params[:user][:role] == 3 then render :action => "editdriver" else render :action => "editclient" end
    
  end
  
  def show
    @user = User.new
    @order = Order.new
  end
  
  def index
    @user = User.new
    @order = Order.new
  end
  
  def login
    
    @order = Order.new
    @user = User.new
    
    session[:current_user] = nil
    
    if !session[:current_user]
      
      user = User.find_by("email = ? AND passwd = ? AND state_driver != ? ",  params[:user][:email], params[:user][:passwd], "Anulado")
      session[:current_user] = user
      
      if session[:current_user]
        if user.role == "1"
           redirect_to order_admin_url
        elsif user.role == "2"
           redirect_to order_client_url
        elsif user.role == "3"
           redirect_to order_driver_url
        else
          redirect_to root_url
        end
      
      else
        redirect_to root_url
      end
      
    else
      redirect_to root_url
    end
  end

  def logout
    session[:current_user] = nil
    redirect_to root_url
  end

end

taxiapp/app/helpers/user_helper.rb
module UserHelper
end

taxiapp/app/views/user/editclient.html.erb
<div class="container">
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center">Modificar Perfil</h1>
        <hr>
    </div>
</div>

<br/>
<br/>
<br/>
<br/>

<div class="row">
  <div class="col-md-4 col-sm-3 col-xs-1"></div>
  <div class="col-md-4 col-sm-6 col-xs-10">
      
      <%= form_for @user, url: user_update_path(@user) do |f| %>
      
          <div class="form-group">
               <label class="frm-title">Cuenta</label>
          </div>
          
          <div class="form-group">
            <label for="email">Email address</label>
              <%= f.text_field :email,  :class => 'form-control', :placeholder => 'Email' %>
          </div>
          
          <div class="form-group">
            <label for="passwd">Password</label>
            <%= f.password_field :passwd,  :class => 'form-control', :placeholder => 'Password' %>
          </div>
          
          <br/>
          
          <div class="form-group">
               <label class="frm-title">Perfil</label>
          </div>
          
          <div class="form-group">
            <label for="first_name">Nombre</label>
            <%= f.text_field :first_name,  :class => 'form-control', :placeholder => 'Nombre' %>
          </div>
          
          <div class="form-group">
            <label for="last_name">Apellidos</label>
            <%= f.text_field :last_name,  :class => 'form-control', :placeholder => 'Apellido' %>
          </div>
          
          <div class="form-group">
            <label for="phone">Celular</label>
            <%= f.text_field :phone,  :class => 'form-control', :placeholder => 'Celular' %>
          </div>
          
          <br/>
          
            <div class="form-group">
               <label class="frm-title">Pago</label>
            </div>
          
          
        <div class="form-group">
            <label for="credit_card">Numero de Tarjeta</label>
            <%= f.text_field :credit_card,  :class => 'form-control', :placeholder => 'Numero de Tarjeta' %>
        </div>
          
        <div class="form-group">
            <div class="container-fluid frm-padding" >
                <div class="col-xs-7 frm-padding">
                <label for="expiration_credit_card">Fecha de Vencimiento</label>
                <%= f.text_field :expiration_credit_card,  :class => 'form-control', :placeholder => 'Fecha de Vencimiento' %>
                </div>
                
                <div class="col-xs-5 frm-padding">
                <label for="cvv">CVV</label>
                <%= f.text_field :cvv,  :class => 'form-control', :placeholder => 'CVV' %>
                </div>
            </div>
        </div>
        <br/>
        <%= f.hidden_field :role, :value => "2" %>
        <%= f.submit 'Modificar Perfil', :class => 'btn btn-primary btn-lg btn-block' %>
  
    <% end %>
 
  </div>
  <div class="col-md-4 col-sm-3 col-xs-1"></div>
</div>
</div>

taxiapp/app/views/user/editdriver.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Modificar Perfil</h1>
            <hr>
        </div>
    </div>
    
    <div class="row">
      <div class="col-md-4 col-sm-3 col-xs-1"></div>
      <div class="col-md-4 col-sm-6 col-xs-10">
          
          <%= form_for @user, url: user_update_path(@user) do |f| %>
              <div class="form-group">
                   <label class="frm-title">Cuenta</label>
              </div>
              
              <div class="form-group">
                <label for="email">Email address</label>
                  <%= f.text_field :email,  :class => 'form-control', :placeholder => 'Email' %>
              </div>
              <div class="form-group">
                <label for="passwd">Password</label>
                <%= f.password_field :passwd,  :class => 'form-control', :placeholder => 'Password' %>
              </div>
              
              <br/>
              <div class="form-group">
                   <label class="frm-title">Perfil</label>
              </div>
              <div class="form-group">
                <label for="first_name">Nombre</label>
                <%= f.text_field :first_name,  :class => 'form-control', :placeholder => 'Nombre' %>
              </div>
              <div class="form-group">
                <label for="last_name">Apellidos</label>
                <%= f.text_field :last_name,  :class => 'form-control', :placeholder => 'Apellido' %>
              </div>
              
                <div class="form-group">
                <label for="phone">Celular</label>
                <%= f.text_field :phone,  :class => 'form-control', :placeholder => 'Celular' %>
              </div>
              
              <br/>
            <div class="form-group">
               <label class="frm-title">Pago</label>
            </div>
              
              
              <div class="form-group">
                <label for="credit_card">Numero de Tarjeta</label>
                <%= f.text_field :credit_card,  :class => 'form-control', :placeholder => 'Numero de Tarjeta' %>
              </div>
              
                <div class="form-group">
                    <div class="container-fluid frm-padding" >
                        <div class="col-xs-7 frm-padding">
                        <label for="expiration_credit_card">Fecha de Vencimiento</label>
                        <%= f.text_field :expiration_credit_card,  :class => 'form-control', :placeholder => 'Fecha de Vencimiento' %>
                        </div>
                        
                        <div class="col-xs-5 frm-padding">
                        <label for="cvv">CVV</label>
                        <%= f.text_field :cvv,  :class => 'form-control', :placeholder => 'CVV' %>
                        </div>
                    </div>
                </div>
                <br/>
                                  
              <div class="form-group">
                   <label class="frm-title">Documentacion</label>
              </div>
              
              <div class="form-group">
                <label for="license">Licencia</label>
                <%= f.text_field :license,  :class => 'form-control', :placeholder => 'Licencia' %>
              </div>
              <div class="form-group">
                <label for="soat">Soat</label>
                <%= f.text_field :soat,  :class => 'form-control', :placeholder => 'Soat' %>
              </div>
              
              <br/>
              <div class="form-group">
                   <label class="frm-title">Vehiculo</label>
              </div>
              <div class="form-group">
                <label for="brand">Marca</label>
                <%= f.text_field :brand,  :class => 'form-control', :placeholder => 'Marca' %>
              </div>
              <div class="form-group">
                <label for="modele">Modelo</label>
                <%= f.text_field :modele,  :class => 'form-control', :placeholder => 'Modelo' %>
              </div>
              
                <div class="form-group">
                <label for="plate">Placa</label>
                <%= f.text_field :plate,  :class => 'form-control', :placeholder => 'Placa' %>
              </div>           
               <%= f.hidden_field :role, :value => "3" %>
               <%= f.submit 'Modificar Perfil', :class => 'btn btn-primary btn-lg btn-block' %>
          <% end %>
        
        
          
      </div>
      <div class="col-md-4 col-sm-3 col-xs-1"></div>
    </div>
</div>

taxiapp/app/views/user/index.html.erb
<h6 class="text-center">COMPLETA ESTOS CAMPOS PARA INGRESAR</h6>
<%= form_for @user, :html => {:class => "col-md-10 col-md-offset-1 col-xs-12 col-xs-offset-0"}, url: user_login_path(@user) do |f| %>
    <div class="form-group">
        <%= f.text_field :email,  :class => 'form-control', :placeholder => 'Email' %>
    </div>
    <div class="form-group">
        <%= f.text_field :passwd,  :class => 'form-control', :placeholder => 'Password' %>
    </div>
    <div class="form-group">
        <%= f.submit 'Ingresa', :class => 'btn btn-primary btn-lg btn-block' %>
        <span class="pull-right"><a href="/register">Registro</a></span><span><a href="#">Ayuda?</a></span>
    </div>
<% end %>
 

taxiapp/app/views/user/newclient.html.erb
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center">Registro Cliente</h1>
        <hr>
    </div>
</div>

<br/>
<br/>
<br/>
<br/>

<div class="row">
  <div class="col-md-4 col-sm-3 col-xs-1"></div>
  <div class="col-md-4 col-sm-6 col-xs-10">
      
      <%= form_for @user, url: user_create_path(@user) do |f| %>
      
          <div class="form-group">
               <label class="frm-title">Cuenta</label>
          </div>
          
          <div class="form-group">
            <label for="email">Email address</label>
              <%= f.text_field :email,  :class => 'form-control', :placeholder => 'Email' %>
          </div>
          
          <div class="form-group">
            <label for="passwd">Password</label>
            <%= f.password_field :passwd,  :class => 'form-control', :placeholder => 'Password' %>
          </div>
          
          <br/>
          
          <div class="form-group">
               <label class="frm-title">Perfil</label>
          </div>
          
          <div class="form-group">
            <label for="first_name">Nombre</label>
            <%= f.text_field :first_name,  :class => 'form-control', :placeholder => 'Nombre' %>
          </div>
          
          <div class="form-group">
            <label for="last_name">Apellidos</label>
            <%= f.text_field :last_name,  :class => 'form-control', :placeholder => 'Apellido' %>
          </div>
          
          <div class="form-group">
            <label for="phone">Celular</label>
            <%= f.text_field :phone,  :class => 'form-control', :placeholder => 'Celular' %>
          </div>
          
          <br/>
          
            <div class="form-group">
               <label class="frm-title">Pago</label>
            </div>
          
          
        <div class="form-group">
            <label for="credit_card">Numero de Tarjeta</label>
            <%= f.text_field :credit_card,  :class => 'form-control', :placeholder => 'Numero de Tarjeta' %>
        </div>
          
        <div class="form-group">
            <div class="container-fluid frm-padding" >
                <div class="col-xs-7 frm-padding">
                <label for="expiration_credit_card">Fecha de Vencimiento</label>
                <%= f.text_field :expiration_credit_card,  :class => 'form-control', :placeholder => 'Fecha de Vencimiento' %>
                </div>
                
                <div class="col-xs-5 frm-padding">
                <label for="cvv">CVV</label>
                <%= f.text_field :cvv,  :class => 'form-control', :placeholder => 'CVV' %>
                </div>
            </div>
        </div>
        <br/>
        <%= f.hidden_field :role, :value => "2" %>
        <%= f.submit 'Estas Listo', :class => 'btn btn-primary btn-lg btn-block' %>
  
    <% end %>
 
  </div>
  <div class="col-md-4 col-sm-3 col-xs-1"></div>
</div>

taxiapp/app/views/user/newdriver.html.erb
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center">Registro Chofer</h1>
        <hr>
    </div>
</div>

<br/>
<br/>
<br/>
<br/>

<div class="row">
  <div class="col-md-4 col-sm-3 col-xs-1"></div>
  <div class="col-md-4 col-sm-6 col-xs-10">
      
      <%= form_for @user, url: user_create_path(@user) do |f| %>
          <div class="form-group">
               <label class="frm-title">Cuenta</label>
          </div>
          
          <div class="form-group">
            <label for="email">Email address</label>
              <%= f.text_field :email,  :class => 'form-control', :placeholder => 'Email' %>
          </div>
          <div class="form-group">
            <label for="passwd">Password</label>
            <%= f.password_field :passwd,  :class => 'form-control', :placeholder => 'Password' %>
          </div>
          
          <br/>
          <div class="form-group">
               <label class="frm-title">Perfil</label>
          </div>
          <div class="form-group">
            <label for="first_name">Nombre</label>
            <%= f.text_field :first_name,  :class => 'form-control', :placeholder => 'Nombre' %>
          </div>
          <div class="form-group">
            <label for="last_name">Apellidos</label>
            <%= f.text_field :last_name,  :class => 'form-control', :placeholder => 'Apellido' %>
          </div>
          
            <div class="form-group">
            <label for="phone">Celular</label>
            <%= f.text_field :phone,  :class => 'form-control', :placeholder => 'Celular' %>
          </div>
          
          <br/>
        <div class="form-group">
           <label class="frm-title">Pago</label>
        </div>
          
          
          <div class="form-group">
            <label for="credit_card">Numero de Tarjeta</label>
            <%= f.text_field :credit_card,  :class => 'form-control', :placeholder => 'Numero de Tarjeta' %>
          </div>
          
            <div class="form-group">
                <div class="container-fluid frm-padding" >
                    <div class="col-xs-7 frm-padding">
                    <label for="expiration_credit_card">Fecha de Vencimiento</label>
                    <%= f.text_field :expiration_credit_card,  :class => 'form-control', :placeholder => 'Fecha de Vencimiento' %>
                    </div>
                    
                    <div class="col-xs-5 frm-padding">
                    <label for="cvv">CVV</label>
                    <%= f.text_field :cvv,  :class => 'form-control', :placeholder => 'CVV' %>
                    </div>
                </div>
            </div>
            <br/>
                              
          <div class="form-group">
               <label class="frm-title">Documentacion</label>
          </div>
          
          <div class="form-group">
            <label for="license">Licencia</label>
            <%= f.text_field :license,  :class => 'form-control', :placeholder => 'Licencia' %>
          </div>
          <div class="form-group">
            <label for="soat">Soat</label>
            <%= f.text_field :soat,  :class => 'form-control', :placeholder => 'Soat' %>
          </div>
          
          <br/>
          <div class="form-group">
               <label class="frm-title">Vehiculo</label>
          </div>
          <div class="form-group">
            <label for="brand">Marca</label>
            <%= f.text_field :brand,  :class => 'form-control', :placeholder => 'Marca' %>
          </div>
          <div class="form-group">
            <label for="modele">Modelo</label>
            <%= f.text_field :modele,  :class => 'form-control', :placeholder => 'Modelo' %>
          </div>
          
            <div class="form-group">
            <label for="plate">Placa</label>
            <%= f.text_field :plate,  :class => 'form-control', :placeholder => 'Placa' %>
          </div>           
           <%= f.hidden_field :role, :value => "3" %>
           <%= f.submit 'Empieza a ganar DINERO', :class => 'btn btn-primary btn-lg btn-block' %>
      <% end %>
    
    
      
  </div>
  <div class="col-md-4 col-sm-3 col-xs-1"></div>
</div>