taxiapp/config/routes.rb
Rails.application.routes.draw do

  get 'order/client'
  root 'pages#home'
  get 'pages/home'
  get 'pages/viaja'
  get 'pages/conduce'
  get 'pages/contacto'
  get 'user/index'
  get 'user/newclient'
  get 'user/newdriver'
  post 'user/create'
  get 'user/editclient'
  get 'user/editdriver'
  post 'user/update'
  post 'user/login'
  get 'user/logout'
  get 'user/show'
  
  resources :user

  get 'order/admin'
  get 'order/driver'
  post 'order/create'
  get 'order/historialclient'
  get 'order/historialdriver'
  get 'order/edit'
  post 'order/update'
  get 'order/dash'
  get 'order/reportclient'
  get 'order/reportorder'
  post 'order/changecli'
  post 'order/cancelcli'
  post 'order/canceldri'
  post 'order/edituseradmin'
  post 'order/deluseradmin'
  post 'order/editorderadmin'
  post 'order/delorderadmin'
  post 'order/editordercli'
  post 'order/delordercli'
  post 'order/delorderdri'
  
  resources :order
  
  
   

end

taxiapp/app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :user
    validates :address_origin, presence: true
    validates :address_destination, presence: true
    validates :time_estimated, presence: true
end

taxiapp/app/controllers/order_controller.rb
class OrderController < ApplicationController
  
  def admin
     @user = User.new
     @order = Order.new
  end
  
  def reportclient
     @user = User.new
     @order = Order.new
     @users = ActiveRecord::Base.connection.execute("SELECT * 
                                                        FROM users o 
                                                        ORDER BY o.created_at ASC")
  end
  
  def reportorder
     @user = User.new
     @order = Order.new
     @orders = ActiveRecord::Base.connection.execute("SELECT o.*, d.*, c.*, o.id AS orderid 
                                                        FROM orders o 
                                                        LEFT JOIN users d ON o.user_driver = d.id
                                                        INNER JOIN users c ON o.user_client = c.id
                                                        ORDER BY o.created_at ASC")
  end
  
  def client
    @user = User.new
    @order = Order.new
    @orders = ActiveRecord::Base.connection.execute("SELECT o.*, u.*, o.id AS orderid
                                                        FROM orders o 
                                                        LEFT JOIN users u ON o.user_client = u.id 
                                                        WHERE o.user_client = '#{session[:current_user]['id']}' AND o.state != 'Terminado' 
                                                        ORDER BY o.created_at 
                                                        ASC LIMIT 3")
  end
  
  def driver
    @user = User.new
    
    user = User.find(session[:current_user]['id'])
    
    if(user.state_driver == "Libre")
      order = ActiveRecord::Base.connection.execute("SELECT o.*, o.id AS orderid
                                                        FROM orders o 
                                                        WHERE o.state = 'Pendiente' 
                                                        ORDER BY o.id DESC")
    else
      order = ActiveRecord::Base.connection.execute("SELECT o.*, u.*, o.id AS orderid
                                                        FROM orders o 
                                                        LEFT JOIN users u ON o.user_driver = u.id 
                                                        WHERE o.user_driver = '#{session[:current_user]['id']}' AND o.state != 'Pendiente' AND u.state_driver = 'Ocupado'")
    end
    
    @order = Order.new
    order.each(:as => :hash) do |row, index|
      @order.id = row["orderid"]
      @order.address_origin = row["address_origin"]
      @order.address_destination = row["address_destination"]
      @order.reference = row["reference"]
      @order.time_estimated = row["time_estimated"]
      @order.state = row["state"]
      @order.payment_type = row["payment_type"]
    end
    
    @orders = ActiveRecord::Base.connection.execute("SELECT * 
                                                        FROM orders o 
                                                        LEFT JOIN users u ON o.user_driver = u.id 
                                                        WHERE o.user_driver = '#{session[:current_user]['id']}' AND o.state != 'Pendiente' 
                                                        ORDER BY o.created_at DESC 
                                                        LIMIT 1")
  end
  
  def historialclient
    @order = Order.new
    @user = User.new
    @orders = ActiveRecord::Base.connection.execute("SELECT * 
                                                        FROM orders o 
                                                        LEFT JOIN users u ON o.user_driver = u.id 
                                                        WHERE o.user_client = '#{session[:current_user]['id']}'")
    
    if(!@orders)
      @orders = Order.new   
    end 
  end
  
  def historialdriver
    @order = Order.new
    @user = User.new
    @orders = ActiveRecord::Base.connection.execute("SELECT * 
                                                        FROM orders o 
                                                        LEFT JOIN users u ON o.user_driver = u.id 
                                                        WHERE o.user_driver = '#{session[:current_user]['id']}'")
    
    if(!@orders)
      @orders = Order.new   
    end 
  end
  
  def orderall
    @order = Order.new
    orders = ActiveRecord::Base.connection.execute("SELECT * 
                                                        FROM orders o 
                                                        LEFT JOIN users u ON o.user_driver = u.id 
                                                        WHERE o.user_client = '#{session[:current_user]['id']}' AND o.state != 'Terminado' 
                                                        ORDER BY o.created_at 
                                                        ASC LIMIT 3")
    return orders
  end
  
  def new
    @user = User.new
    @order = Order.new
  end
  
  ##Busca ordenes pendientes para mostralo en el chofer o mostrar la orden que confirmo
  def show
    @user = User.new
    @order = Order.find_by state: 'Pendiente'
     
    if(!@order)
      @order = Order.new   
    end 
  end
  
  ##Crea ordenes
  def create
    @user = User.new
    @order = Order.new
    @orders = orderall
    
    if params[:order][:address_origin] != ""
      if params[:order][:address_destination] != ""
        if params[:order][:time_estimated] != ""
    
          @order = Order.new(user_client:session[:current_user]['id'], 
                           address_origin:params[:order][:address_origin],
                           address_destination:params[:order][:address_destination],
                           reference:params[:order][:reference],
                           state:"Pendiente",
                           time_estimated:params[:order][:time_estimated],
                           payment_type:params[:order][:payment_type],
                           promotion_code:params[:order][:promotion_code])
                           
          if @order.save()
            @alertType = "success"
            @alertMessage = "Su pedido sera confirmado dentro de poco, sea paciente, gracias!."
            
            @orders = ActiveRecord::Base.connection.execute("SELECT * 
                                                        FROM orders o 
                                                        LEFT JOIN users u ON o.user_client = u.id 
                                                        WHERE o.user_client = '#{session[:current_user]['id']}' AND o.state != 'Terminado' 
                                                        ORDER BY o.created_at 
                                                        ASC LIMIT 3")
                                                        
            @order = Order.new
            
          end  
          
        elsif
          @alertType = "danger"
          @alertMessage = "Por favor el punto de encuentro, origen."
        end
        
      elsif
        @alertType = "danger"
        @alertMessage = "Por favor ingrese el lugar de destino."
      end
    
    elsif
      @alertType = "danger"
      @alertMessage = "Por favor ingrese el tiempo estimado de llegaba del taxi."
    end
    
    render :action => "client"
  end
  
  ##Confirmacion de orden, iniciar y terminar la orden de acuerdo al estado
  def update
    
    @user = User.new
    @order = Order.find(params[:order][:id])
    
    if @order.state == "Pendiente"
    
      user = User.find(session[:current_user]['id'])
      user.state_driver = "Ocupado"
      user.save()
      
      @order.user_driver = session[:current_user]['id']
      @order.state = 'Confirmado'
      @order.save
    
    elsif @order.state == "Confirmado"
    
      @order.state = 'Iniciado'
      @order.start_time = Time.current.to_s
      @order.save
      
    elsif @order.state == "Iniciado"
    
      @order.state = 'Terminado'
      @order.end_time = Time.current.to_s
      @order.amount = ((@order.end_time.to_time.to_i - @order.start_time.to_time.to_i) * 0.01) + 5
      #@order.amount = 0
      @order.save
      
      user = User.find(session[:current_user]['id'])
      user.state_driver = "Libre"
      user.save()
    
    end
    
    redirect_to("/order/driver")
  end
  
  def openorder
    @order = Order.new
  end
  
  def changecli
    @order = Order.new
  end
  
  def cancelcli
    @order = Order.new
  end
  
  def canceldri
    @order = Order.new
  end
  
  def edituseradmin
    @order = Order.new
    @user = User.new
    
    if params[:user][:first_name] != ""
      if params[:user][:credit_card] != ""
        if params[:user][:expiration_credit_card] != ""
          if params[:user][:cvv] != ""

            @user = User.find(params[:user][:id])
            @user.first_name = params[:user][:first_name]
            @user.last_name = params[:user][:last_name]
            @user.phone = params[:user][:phone]
            @user.credit_card = params[:user][:credit_card]
            @user.expiration_credit_card = params[:user][:expiration_credit_card]
            @user.cvv = params[:user][:cvv]
            @user.license = params[:user][:license]
            @user.state_driver = params[:user][:state_driver]
                             
            if @user.save()
              redirect_to(:back)
            end
            
          elsif
            @alertType = "danger"
            @alertMessage = "Por favor ingrese el codigo secreto de su tardejeta de credito."
          end
            
        elsif
          @alertType = "danger"
          @alertMessage = "Por favor ingrese la fecha de caducidad de la tardejeta de credito."
        end
          
      elsif
        @alertType = "danger"
        @alertMessage = "Por favor ingrese el numero de su tarjeta."
      end
        
    elsif
      @alertType = "danger"
      @alertMessage = "Por favor ingrese sus nombres."
    end
  end
  
  def deluseradmin

taxiapp/app/helpers/order_helper.rb
module OrderHelper
end

taxiapp/app/views/order/admin.html.erb
<canvas id="myChart" width="400" height="400"></canvas>


<script>
var ctx = document.getElementById("myChart").getContext("2d");

    var myLineChart = new Chart(ctx).Line(data, options);
    
    var data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
            {
                label: "My First dataset",
                fillColor: "rgba(220,220,220,0.2)",
                strokeColor: "rgba(220,220,220,1)",
                pointColor: "rgba(220,220,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: [65, 59, 80, 81, 56, 55, 40]
            },
            {
                label: "My Second dataset",
                fillColor: "rgba(151,187,205,0.2)",
                strokeColor: "rgba(151,187,205,1)",
                pointColor: "rgba(151,187,205,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(151,187,205,1)",
                data: [28, 48, 40, 19, 86, 27, 90]
            }
        ]
    };
    
    var options = {

    ///Boolean - Whether grid lines are shown across the chart
    scaleShowGridLines : true,

    //String - Colour of the grid lines
    scaleGridLineColor : "rgba(0,0,0,.05)",

    //Number - Width of the grid lines
    scaleGridLineWidth : 1,

    //Boolean - Whether to show horizontal lines (except X axis)
    scaleShowHorizontalLines: true,

    //Boolean - Whether to show vertical lines (except Y axis)
    scaleShowVerticalLines: true,

    //Boolean - Whether the line is curved between points
    bezierCurve : true,

    //Number - Tension of the bezier curve between points
    bezierCurveTension : 0.4,

    //Boolean - Whether to show a dot for each point
    pointDot : true,

    //Number - Radius of each point dot in pixels
    pointDotRadius : 4,

    //Number - Pixel width of point dot stroke
    pointDotStrokeWidth : 1,

    //Number - amount extra to add to the radius to cater for hit detection outside the drawn point
    pointHitDetectionRadius : 20,

    //Boolean - Whether to show a stroke for datasets
    datasetStroke : true,

    //Number - Pixel width of dataset stroke
    datasetStrokeWidth : 2,

    //Boolean - Whether to fill the dataset with a colour
    datasetFill : true,

    //String - A legend template
    legendTemplate : ""

};
</script>

taxiapp/app/views/order/client.html.erb
<div id="page-content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center">Pedir Taxi Express</h1>
                <hr>
            </div>
        </div>
        
        <br/>
        <br/>
        <br/>
        <br/>
        
        <div class="row">
            <div class="col-md-7">
                <%= form_for @order, url: order_create_path(@order) do |f| %>
                    <div class="row">
                
                        <div class="row form-group">
                            <div class="col-sm-1"></div>
                            <div class="col-sm-10">
                                <%= f.text_field :address_origin,  :class => 'form-control', :placeholder => 'Origen' %>
                            </div>
                            <div class="col-sm-1"></div>
                        </div>
                        <div class="row form-group">
                            <div class="col-sm-1"></div>
                            <div class="col-sm-10">
                                <%= f.text_field :address_destination,  :class => 'form-control', :placeholder => 'Destino' %>
                            </div>
                            <div class="col-sm-1"></div>
                        </div>
                        
                          <div class="row form-group">
                            <div class="col-sm-1"></div>
                            <div class="col-sm-10">
                                <%= f.text_field :reference,  :class => 'form-control', :placeholder => 'Referencia' %>
                            </div>
                            <div class="col-sm-1"></div>
                         </div>
                         
                        <div class="row form-group">
                            <div class="col-sm-1"></div>
                            <div class="col-sm-5">
                                <%= f.text_field :time_estimated,  :class => 'form-control', :placeholder => 'Estimado' %>
                            </div>
                            <div class="col-sm-5">
                                <%= f.text_field :payment_type,  :class => 'form-control', :placeholder => 'Pago' %>
                            </div>
                            <div class="col-sm-1"></div>
                        </div>
                        
                        <div class="row form-group">
                            <div class="col-sm-1"></div>
                            <div class="col-sm-10">
                                <%= f.submit 'Pedir YA!', :class => 'btn btn-primary btn-lg btn-block' %>
                            </div>
                            <div class="col-sm-1"></div>
                        </div>
                        
                    </div>
                <% end %>
            </div>
            <div class="col-md-5">
                <iframe  width="400" height="240" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=Universidad%20Peruana%20de%20Ciencias%20Aplicadas&key=AIzaSyAEz6ZPTS0y5N4hnuVx2nVqlK2tXsfftmQ" allowfullscreen></iframe>                    
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Origen</th>
                            <th>Destino</th>
                            <th>Estado</th>
                            <th>Estimado</th>
                            <th>Chofer</th>
                            <th>Pago</th>
                            <th>Inicio</th>
                            <th>Fin</th>
                            <th>Importe</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @orders.each(:as => :hash) do |row, index| %>
                        <tr>
                            <td><%= row["address_origin"] %></td>
                            <td><%= row["address_destination"] %></td>
                            <td><%= row["state"] %></td>
                            <td><%= row["time_estimated"] %> min aprox.</td>
                            <td><%= row["first_name"] %></td>
                            <td><%= row["payment_type"] %></td>
                            <td><%= row["start_time"] %></td>
                            <td><%= row["end_time"] %></td>
                            <td><%= row["amount"] %></td>
                            <td>
                                <a class="btn btn-success" onclick="editOrderCli(this)" 
                                                            data-addressorigin="<%= row["address_origin"] %>"
                                                            data-addressdestination="<%= row["address_destination"] %>"
                                                            data-reference="<%= row["reference"] %>"
                                                            data-paymenttype="<%= row["payment_type"] %>"
                                                            data-timeestimated="<%= row["time_estimated"] %>"
                                                            data-idorder="<%= row["orderid"] %>"
                                                            data-toggle="modal" 
                                                            data-target="#modalordereditcli" title="Modificar orden"><i class="fa fa-pencil"></i></a>
                                <a class="btn btn-danger" onclick="delOrderCli(this)" 
                                                            data-idorder="<%= row["orderid"] %>"
                                                            data-toggle="modal" 
                                                            data-target="#modalorderdelcli" title="Anular orden"><i class="fa fa-close"></i></a>
                            </td>
                        </tr>    
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
function editOrderCli(obj){

    $(".address_origin").val($(obj).attr('data-addressorigin'));
    $(".address_destination").val($(obj).attr('data-addressdestination'));
    $(".payment_type").val($(obj).attr('data-paymenttype'));
    $(".time_estimated").val($(obj).attr('data-timeestimated'));
    $(".reference").val($(obj).attr('data-reference'));
    $(".idorder").val($(obj).attr('data-idorder'));
    
}

function delOrderCli(obj){
    $(".idorder").text($(obj).attr('data-idorder'));
    $(".idorder").val($(obj).attr('data-idorder'));
}
</script>

taxiapp/app/views/order/driver.html.erb
<div id="page-content-wrapper">
    <div class="container">
        
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center">Mis Pedidos</h1>
                <hr>
            </div>
        </div>
        
        <br/>
        <br/>
        
        <div class="row">
            <div class="col-md-5">
                <%= form_for @order, url: order_update_path(@order) do |f| %>
                    <table class="table">
                        <tbody>
                            <tr>
                                <td style="border-top:none"><strong>MI PEDIDO EN ATENCION : </strong></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-home" style="color:green;"></i> <b>&nbsp; De :  </b> <%= @order.address_origin %> </td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-taxi" style="color:orange;"></i> <b>&nbsp; Hacia :  </b> <%= @order.address_destination %> </td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-bank" style="color:blue;"></i> <b>&nbsp; Referencia :  </b> <%= @order.reference %> </td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-clock-o" style="color:white;"></i> <b>&nbsp; Dentro de :  </b> <%= @order.time_estimated %> min aprox.</td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-flag" style="color:red;"></i> <b>&nbsp; Estado :  </b> <%= @order.state %> </td>
                            </tr>
                            <tr>
                                <td>
                                    <%= f.hidden_field :id, :value => @order.id %>
                                    
                                    <% if @order.state == "Confirmado" %>
                                        <%= f.submit 'Iniciar Recorredo', :class => 'btn btn-primary btn-lg btn-block' %>
                                    <% elsif @order.state == "Iniciado" %>
                                        <%= f.submit 'Terminar Pedido', :class => 'btn btn-danger btn-lg btn-block' %>
                                    <% elsif  @order.state == "Pendiente" %>
                                        <%= f.submit 'Confirmar Orden', :class => 'btn btn-success btn-lg btn-block' %>
                                        <a class="btn btn-danger btn-lg btn-block" onclick="delOrderDri(this)" 
                                                            data-idorder="<%= @order.id %>"
                                                            data-toggle="modal" 
                                                            data-target="#modalorderdeldri" title="Anular orden">Pasar Pedido</a>
                                    <% end %>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                <% end %>
            </div>
            
            <div class="col-md-7">
                <iframe  width="640" height="320" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=Universidad%20Peruana%20de%20Ciencias%20Aplicadas&key=AIzaSyAEz6ZPTS0y5N4hnuVx2nVqlK2tXsfftmQ" allowfullscreen></iframe>                    
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Origen</th>
                            <th>Destino</th>
                            <th>Estado</th>
                            <th>Promocion</th>
                            <th>Chofer</th>
                            <th>Vehiculo</th>
                            <th>Inicio</th>
                            <th>Fin</th>
                            <th>Importe</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @orders.each(:as => :hash) do |row, index| %>
                        <tr>
                            <td><%= row["address_origin"] %></td>
                            <td><%= row["address_destination"] %></td>
                            <td><%= row["state"] %></td>
                            <td><%= row["promotion_code"] %></td>
                            <td><%= row["first_name"] %></td>
                            <td><%= row["brand"] %></td>
                            <td><%= row["start_time"] %></td>
                            <td><%= row["end_time"] %></td>
                            <td>S/. <%= row["amount"] %></td>
                        </tr>    
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>
</div>

<script>
function delOrderDri(obj){
    $(".idorder").text($(obj).attr('data-idorder'));
    $(".idorder").val($(obj).attr('data-idorder'));
}
</script>

taxiapp/app/views/order/historialclient.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Mis Pedidos</h1>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Origen</th>
                        <th>Destino</th>
                        <th>Estado</th>
                        <th>Estimado</th>
                        <th>Chofer</th>
                        <th>Pago</th>
                        <th>Inicio</th>
                        <th>Fin</th>
                        <th>Importe</th>
                    </tr>
                </thead>
                <tbody>
                    <% @orders.each(:as => :hash) do |row, index| %>
                    <tr>
                        <td><%= row["address_origin"] %></td>
                        <td><%= row["address_destination"] %></td>
                        <td><%= row["state"] %></td>
                        <td><%= row["time_estimated"] %> min aprox.</td>
                        <td><%= row["first_name"] %></td>
                        <td><%= row["payment_type"] %></td>
                        <td><%= row["start_time"] %></td>
                        <td><%= row["end_time"] %></td>
                        <td>S/. <%= row["amount"] %></td>
                    </tr>    
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

taxiapp/app/views/order/historialdriver.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Mis Carreras</h1>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Origen</th>
                        <th>Destino</th>
                        <th>Referencia</th>
                        <th>Estado</th>
                        <th>Estimado</th>
                        <th>Pago</th>
                        <th>Inicio</th>
                        <th>Fin</th>
                        <th>Importe</th>
                    </tr>
                </thead>
                <tbody>
                    <% @orders.each(:as => :hash) do |row, index| %>
                    <tr>
                        <td><%= row["address_origin"] %></td>
                        <td><%= row["address_destination"] %></td>
                        <td><%= row["reference"] %></td>
                        <td><%= row["state"] %></td>
                        <td><%= row["time_estimated"] %> min aprox.</td>
                        <td><%= row["payment_type"] %></td>
                        <td><%= row["start_time"] %></td>
                        <td><%= row["end_time"] %></td>
                        <td>S/. <%= row["amount"] %></td>
                    </tr>    
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>