taxiapp/config/routes.rb
Rails.application.routes.draw do

  get 'order/client'
  root 'pages#home'
  get 'pages/home'
  get 'pages/viaja'
  get 'pages/conduce'
  get 'pages/contacto'
  get 'user/index'
  get 'user/newclient'
  get 'user/newdriver'
  post 'user/create'
  get 'user/editclient'
  get 'user/editdriver'
  post 'user/update'
  post 'user/login'
  get 'user/logout'
  get 'user/show'
  
  resources :user

  get 'order/admin'
  get 'order/driver'
  post 'order/create'
  get 'order/historialclient'
  get 'order/historialdriver'
  get 'order/edit'
  post 'order/update'
  get 'order/dash'
  get 'order/reportclient'
  get 'order/reportorder'
  post 'order/changecli'
  post 'order/cancelcli'
  post 'order/canceldri'
  post 'order/edituseradmin'
  post 'order/deluseradmin'
  post 'order/editorderadmin'
  post 'order/delorderadmin'
  post 'order/editordercli'
  post 'order/delordercli'
  post 'order/delorderdri'
  
  resources :order
  
  
   

end

taxiapp/app/views/layouts/_alert.html.erb
<% if @alertType && @alertMessage %>
<div class="alert alert-<%= @alertType %>" role="alert" style="position:absolute;; margin-top:135px; width:600px; margin-left:50%; left:-300px; z-index:1000;">
    <%= @alertMessage %>
</div>
<% end %>

taxiapp/app/views/layouts/_login.html.erb
<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h2 class="text-center"><i class="fa fa-user-secret fa-4x" ></i><br>LOGIN</h2>
            </div>
            <div class="modal-body row">
                <h6 class="text-center">COMPLETA ESTOS CAMPOS PARA INGRESAR</h6>
                <%= form_for @user, :html => {:class => "col-md-10 col-md-offset-1 col-xs-12 col-xs-offset-0"}, url: user_login_path(@user) do |f| %>
                    <div class="form-group">
                        <%= f.text_field :email,  :class => 'form-control', :placeholder => 'Email' %>
                    </div>
                    <div class="form-group">
                        <%= f.password_field :passwd,  :class => 'form-control', :placeholder => 'Password' %>
                    </div>
                    <div class="form-group">
                        <%= f.submit 'Ingresa', :class => 'btn btn-primary btn-lg btn-block' %>
                        <span class="pull-right"></span><span><a href="#">Ayuda?</a></span>
                    </div>
                <% end %>
            </div>
            <div class="modal-footer">
                <h6 class="text-center"><a href="">La privacidad es importante para nosotros.</a></h6>
            </div>
        </div>
    </div>
</div>

taxiapp/app/views/layouts/_menu.html.erb
<li><%= link_to "Viaja", pages_viaja_path  %></li>
<li><%= link_to "Conduce", pages_conduce_path  %></li>
<li><%= link_to "Contacto", pages_contacto_path  %></li>

taxiapp/app/views/layouts/_modal.html.erb
<div class="modal fade" id="modalusereditadmin" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for @user, url: order_edituseradmin_path(@user) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modificar Usuario</h4>
      </div>
      <div class="modal-body">
      <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
          
            <div class="form-group">
              <label for="first_name">Nombre</label>
              <%= f.text_field :first_name,  :class => 'form-control first_name', :placeholder => 'Nombre' %>
            </div>
            
            <div class="form-group">
              <label for="last_name">Apellidos</label>
              <%= f.text_field :last_name,  :class => 'form-control last_name', :placeholder => 'Apellido' %>
            </div>
            
            <div class="form-group">
              <div class="container-fluid frm-padding" >
                <div class="col-xs-5 frm-padding">
                  <label for="phone">Celular</label>
                  <%= f.text_field :phone,  :class => 'form-control phone', :placeholder => 'Celular' %>
                </div>
                <div class="col-xs-7 frm-padding">
                  <label for="state_driver">Estado</label>
                  <%= f.text_field :state_driver,  :class => 'form-control state_driver', :placeholder => 'Estado' %>
                </div>
              </div>
            </div>
            
            <div class="form-group">
                <label for="credit_card">Numero de Tarjeta</label>
                <%= f.text_field :credit_card,  :class => 'form-control credit_card', :placeholder => 'Numero de Tarjeta' %>
            </div>
            
            <div class="form-group">
                <div class="container-fluid frm-padding" >
                    <div class="col-xs-7 frm-padding">
                    <label for="expiration_credit_card">Fecha de Vencimiento</label>
                    <%= f.text_field :expiration_credit_card,  :class => 'form-control expiration_credit_card', :placeholder => 'Fecha de Vencimiento' %>
                    </div>
                    
                    <div class="col-xs-5 frm-padding">
                    <label for="cvv">CVV</label>
                    <%= f.text_field :cvv,  :class => 'form-control cvv', :placeholder => 'CVV' %>
                    </div>
                </div>
            </div>
            
            <%= f.hidden_field :id, :class => 'form-control id' %>
            
            <div class="col-md-1"></div>
          </div>
      </div>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= f.submit 'Guardar', :class => 'btn btn-success' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="modaluserdeladmin" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for @user, url: order_deluseradmin_path(@user) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Eliminar Usuario</h4>
      </div>
      <div class="modal-body">
      <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
          
            <div class="form-group">
              <label for="first_name">Seguro que deseas eliminar al usuario <span class="first_name"></span> con id <span class="id"></span> ?</label>
            </div>

            <%= f.hidden_field :id, :class => 'form-control id' %>
            
            <div class="col-md-1"></div>
          </div>
      </div>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= f.submit 'Eliminar', :class => 'btn btn-danger' %>
      </div>
      <% end %>
    </div>
  </div>
</div>


<!--Order-->

<div class="modal fade" id="modalordereditadmin" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for @order, url: order_editorderadmin_path(@order) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modificar Pedido</h4>
      </div>
      <div class="modal-body">
      <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
          
            <div class="form-group">
              <label for="address_origin">Origen</label>
              <%= f.text_field :address_origin,  :class => 'form-control address_origin', :placeholder => 'Origen' %>
            </div>
            
            <div class="form-group">
              <label for="address_destination">Destino</label>
              <%= f.text_field :address_destination,  :class => 'form-control address_destination', :placeholder => 'Destino' %>
            </div>
            
            <div class="form-group">
                <label for="reference">Referencia</label>
                <%= f.text_field :reference,  :class => 'form-control reference', :placeholder => 'Referencia' %>
            </div>
            
            <div class="form-group">
                <label for="state">Estado</label>
                <%= f.text_field :state,  :class => 'form-control state', :placeholder => 'Estado de la orden' %>
            </div>
            
            <%= f.hidden_field :id, :class => 'form-control idorder' %>
            
            <div class="col-md-1"></div>
          </div>
      </div>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= f.submit 'Guardar', :class => 'btn btn-success' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="modalorderdeladmin" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for @order, url: order_delorderadmin_path(@order) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Eliminar Pedido</h4>
      </div>
      <div class="modal-body">
      <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
          
            <div class="form-group">
              <label for="first_name">Seguro que deseas eliminar el pedido con id <span class="idorder"></span> ?</label>
            </div>

            <%= f.hidden_field :id, :class => 'form-control idorder' %>
            
            <div class="col-md-1"></div>
          </div>
      </div>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= f.submit 'Eliminar', :class => 'btn btn-danger' %>
      </div>
      <% end %>
    </div>
  </div>
</div>


<!--Order cli -->

<div class="modal fade" id="modalordereditcli" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for @order, url: order_editordercli_path(@order) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Editar Pedido</h4>
      </div>
      <div class="modal-body">
      <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
          
            <div class="form-group">
              <label for="address_origin">Origen</label>
              <%= f.text_field :address_origin,  :class => 'form-control address_origin', :placeholder => 'Origen' %>
            </div>
            
            <div class="form-group">
              <label for="address_destination">Destino</label>
              <%= f.text_field :address_destination,  :class => 'form-control address_destination', :placeholder => 'Destino' %>
            </div>
            
            <div class="form-group">
                <label for="reference">Referencia</label>
                <%= f.text_field :reference,  :class => 'form-control reference', :placeholder => 'Referencia' %>
            </div>
            
            <div class="form-group">
                <label for="state">Tiempo Estimado</label>
                <%= f.text_field :time_estimated,  :class => 'form-control time_estimated', :placeholder => 'Tiempo estimado' %>
            </div>
            
            <div class="form-group">
                <label for="state">Forma de Pago</label>
                <%= f.text_field :payment_type,  :class => 'form-control payment_type', :placeholder => 'Forma de Pago' %>
            </div>
            
            <%= f.hidden_field :id, :class => 'form-control idorder' %>
            
            <div class="col-md-1"></div>
          </div>
      </div>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= f.submit 'Guardar', :class => 'btn btn-success' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="modalorderdelcli" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for @order, url: order_delordercli_path(@order) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Cancelar Pedido</h4>
      </div>
      <div class="modal-body">
      <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
          
            <div class="form-group">
              <label for="first_name">Seguro que deseas cancelar el pedido con id <span class="idorder"></span> ?</label>
            </div>

            <%= f.hidden_field :id, :class => 'form-control idorder' %>
            
            <div class="col-md-1"></div>
          </div>
      </div>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= f.submit 'Eliminar', :class => 'btn btn-danger' %>
      </div>
      <% end %>
    </div>
  </div>
</div>


<!--Order Chofer -->

<div class="modal fade" id="modalorderdeldri" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for @order, url: order_delorderdri_path(@order) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Pasar Pedido</h4>
      </div>
      <div class="modal-body">
      <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
          
            <div class="form-group">
              <label for="first_name">Seguro que deseas pasar el pedido con id <span class="idorder"></span> ?</label>
            </div>

            <%= f.hidden_field :id, :class => 'form-control idorder' %>
            
            <div class="col-md-1"></div>
          </div>
      </div>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= f.submit 'Pasar', :class => 'btn btn-danger' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

taxiapp/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-trans navbar-fixed-top" role="navigation">
    
    <% if session[:current_user] %>
        <a href="#menu-toggle" id="menu-toggle"><i class="fa fa-bars ico-slidebar"></i></a>
    <% end %>
    
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsible">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
           
            <a class="navbar-brand" href="/"><i class="fa fa-taxi"></i> TAXI EXPRESS</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar-collapsible">
            <ul class="nav navbar-nav navbar-left">
                <%= render 'layouts/menu' %>
                <li>&nbsp;</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if session[:current_user] %>
                    <li><a href="#"> <i class="fa fa-user"></i> Bienvenido : <%= session[:current_user]['first_name'] %></a></li>
                    <li><a href="/user/logout"> <i class="fa fa-unlock"></i> Log out</a></li>
                <% else %>
                     <li><a href="#" data-toggle="modal" data-target="#myModal"><i class="fa fa-lock"></i> Login</a></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

taxiapp/app/views/layouts/_sidebaradmin.html.erb
<div id="wrapper">
    <div id="sidebar-wrapper" >
        <ul class="sidebar-nav">
            <li>
                <center><i class="fa fa-th-large fa-2x"></i></center>
                <%= link_to "Usuarios", order_reportclient_path  %>
            </li>
            <li>
                <center><i class="fa fa-th-large fa-2x"></i></center>
                <%= link_to "Pedidos", order_reportorder_path  %>
            </li>
            <li>
                <center><i class="fa fa-user fa-2x"></i></center>
                <%= link_to "Perfil", user_editclient_path  %>
            </li>
            <li>
                <center><i class="fa fa-unlock fa-2x"></i></center>
                <%= link_to "Cerrar", user_logout_path  %>
            </li>
        </ul>
    </div>
</div>
        

taxiapp/app/views/layouts/_sidebarcli.html.erb
<div id="wrapper">
    <div id="sidebar-wrapper" >
        <ul class="sidebar-nav">
            <li>
                <center><i class="fa fa-taxi fa-2x"></i></center>
                <%= link_to "Pedir YA!", order_client_path  %>
            </li>
            <li>
                <center><i class="fa fa-list-alt fa-2x"></i></center>
                <%= link_to "Carreras", order_historialclient_path  %>
            </li>
            <li>
                <center><i class="fa fa-user fa-2x"></i></center>
                <%= link_to "Perfil", user_editclient_path  %>
            </li>
            <li>
                <center><i class="fa fa-heart fa-2x"></i></center>
                <%= link_to "Promos", order_historialclient_path  %>
            </li>
            <li>
                <center><i class="fa fa-unlock fa-2x"></i></center>
                <%= link_to "Cerrar", user_logout_path  %>
            </li>
        </ul>
    </div>
</div>
        

taxiapp/app/views/layouts/_sidebardri.html.erb
<div id="wrapper">
    <div id="sidebar-wrapper" >
        <ul class="sidebar-nav">
            <li>
                <center><i class="fa fa-bell fa-2x"></i></center>
                <%= link_to "Alertas!", order_driver_path  %>
            </li>
            <li>
                <center><i class="fa fa-list-alt fa-2x"></i></center>
                <%= link_to "Carreras", order_historialdriver_path  %>
            </li>
            <li>
                <center><i class="fa fa-user fa-2x"></i></center>
                <%= link_to "Perfil", user_editdriver_path  %>
            </li>
            <li>
                <center><i class="fa fa-unlock fa-2x"></i></center>
                <%= link_to "Cerrar", user_logout_path  %>
            </li>
        </ul>
    </div>
</div>

taxiapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Taxiapp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alert' %>
      <section class="container-fluid" style="padding:0; margin-top:50px;" id="section1">
        <% if session[:current_user] %>
          <% if session[:current_user]['role'] == "1" %>
            <%= render 'layouts/sidebaradmin' %>
          <% elsif session[:current_user]['role'] == "2" %>
            <%= render 'layouts/sidebarcli' %>
          <% elsif session[:current_user]['role'] == "3" %>
            <%= render 'layouts/sidebardri' %>
          <% end %>
        <% end %>
        
        <%= yield %>
      </section>
      
      <%= render 'layouts/login' %>
      <%= render 'layouts/modal' %>
      
      <script>
      $("#menu-toggle").click(function(e) {
          e.preventDefault();
          
          var toggle = $("#flagToggle").val();
          $("#wrapper").toggleClass("toggled");
      });
      </script>
  </body>
</html>